//! Windows packaging: a portable folder always, plus a WiX-authored `.msi`.
//!
//! The app binary is self-contained, so the "portable" output is just the
//! `.exe` (+ licence). The `.msi` is generated by writing a `.wxs` authoring
//! file and invoking the **WiX Toolset** (`wix build`, v4 schema) when it's on
//! `PATH`; without WiX we still emit the `.wxs` so it can be built on a machine
//! that has it. WiX v6+ gates use behind the Open Source Maintenance Fee EULA
//! (error `WIX7015`); [`wix_major`] reads the installed major version so
//! [`bundle`] can pass `-acceptEula wix<major>` for a non-interactive CI build.
//!
//! The `.msi` uses `WixUI_InstallDir` (from `WixToolset.UI.wixext`): a real
//! wizard with a licence-agreement page (`License.rtf`, generated from the
//! AGPL text — see [`rtf_document`]), an install-directory chooser, a progress
//! page, and a finish page whose optional checkbox launches the app. Without
//! the UI extension the `.msi` step is skipped (the `.wxs` is still written).

use crate::bundle::Context;
use crate::util::{copy, fresh_dir, have, report, try_run, workspace_root};
use crate::{icon, meta};

/// The arch token for the target being packaged (`None` = the host) — used
/// both as the WiX `-arch` value and as the `-<arch>` suffix on the portable
/// folder / `.msi` file name. Errors on an arch WiX doesn't know rather than
/// silently mislabelling.
fn win_arch(cx: &Context) -> Result<&'static str, String> {
    let arch = match cx.target.as_deref() {
        Some(triple) => triple.split('-').next().unwrap_or(""),
        None => std::env::consts::ARCH,
    };
    match arch {
        "x86_64" => Ok("x64"),
        "aarch64" => Ok("arm64"),
        "x86" => Ok("x86"),
        other => Err(format!(
            "Windows packaging has no WiX arch for `{other}` (target {:?}) — \
             add it to windows::win_arch",
            cx.target
        )),
    }
}

pub fn bundle(cx: &Context) -> Result<(), String> {
    let arch = win_arch(cx)?;

    // ── portable folder ────────────────────────────────────────────────────
    let portable = cx
        .out_dir
        .join(format!("{}-{}-{arch}", meta::SLUG, meta::numeric_version()));
    fresh_dir(&portable).map_err(io)?;
    // The shipped/branded name (meta::DISPLAY_NAME), not the raw cargo build
    // artifact's kebab-case name.
    copy(
        &cx.binary,
        &portable.join(format!("{}.exe", meta::DISPLAY_NAME)),
    )
    .map_err(io)?;
    copy(
        &workspace_root().join("crates/dtb-ke-ui/assets/AGPL-3.0.txt"),
        &portable.join("LICENSE.txt"),
    )
    .ok();
    report(&portable);

    // ── WiX authoring ─────────────────────────────────────────────────────
    let staging = cx.out_dir.join("wix");
    fresh_dir(&staging).map_err(io)?;
    let exe_name = format!("{}.exe", meta::DISPLAY_NAME);
    copy(&cx.binary, &staging.join(&exe_name)).map_err(io)?;

    // Licence: a plain copy shipped into the install dir (AGPL §), plus an
    // RTF the installer's licence-agreement page renders.
    let license_src = workspace_root().join("crates/dtb-ke-ui/assets/AGPL-3.0.txt");
    copy(&license_src, &staging.join("LICENSE.txt")).ok();
    let license_rtf = std::fs::read_to_string(&license_src)
        .map(|t| rtf_document(&t))
        .unwrap_or_else(|_| {
            rtf_document(
                "GNU Affero General Public License v3.\n\
                 See https://www.gnu.org/licenses/agpl-3.0.txt",
            )
        });
    std::fs::write(staging.join("License.rtf"), license_rtf).map_err(io)?;

    let has_icon = cx.have_icon && icon::ico_path().exists();
    if has_icon {
        copy(&icon::ico_path(), &staging.join("AppIcon.ico")).map_err(io)?;
    }

    let wxs = staging.join("Package.wxs");
    std::fs::write(&wxs, wxs_source(&exe_name, has_icon)).map_err(io)?;
    report(&wxs);

    // ── build the .msi ────────────────────────────────────────────────────
    if !cx.wants("msi") {
        eprintln!("dtb-ke-bundle: skipping .msi (--formats doesn't include it)");
        return Ok(());
    }
    if !have("wix") {
        eprintln!(
            "dtb-ke-bundle: `wix` not on PATH — wrote {} but did not build the .msi.\n\
             Install the WiX Toolset (`dotnet tool install --global wix`) and re-run, \
             or build it elsewhere with `wix build {}`.",
            wxs.display(),
            wxs.display()
        );
        return Ok(());
    }
    // The `.wxs` references `WixUI_InstallDir` — no UI extension, no build.
    if !wix_has_ext("WixToolset.UI.wixext") {
        eprintln!(
            "dtb-ke-bundle: WixToolset.UI.wixext not installed — wrote {} but did not build the .msi.\n\
             Install it with `wix extension add -g WixToolset.UI.wixext` and re-run.",
            wxs.display()
        );
        return Ok(());
    }

    let msi = cx.out_dir.join(format!(
        "{}-{}-{arch}.msi",
        meta::SLUG,
        meta::numeric_version()
    ));
    let mut args = vec![
        "build".to_string(),
        wxs.to_string_lossy().into_owned(),
        "-arch".into(),
        arch.to_string(),
        "-ext".into(),
        "WixToolset.UI.wixext".into(),
        "-o".into(),
        msi.to_string_lossy().into_owned(),
    ];
    args.extend(wix_eula_args());
    try_run(
        "wix",
        &args.iter().map(String::as_str).collect::<Vec<_>>(),
        &staging,
    )?;
    report(&msi);
    Ok(())
}

/// The installed WiX Toolset major version (`wix --version` → the leading
/// integer, e.g. `7` from `7.0.1+abc0def`). `None` if `wix` isn't runnable or
/// the output doesn't parse.
fn wix_major() -> Option<u32> {
    let out = std::process::Command::new("wix")
        .arg("--version")
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&out.stdout);
    text.trim().split(['.', '+', '-']).next()?.parse().ok()
}

/// `-acceptEula wix<major>` for WiX v6+ (which blocks every subcommand behind
/// the OSMF EULA — `WIX7015`), empty otherwise. Passed to every `wix` call
/// that touches project state. A one-off acceptance, profile-independent —
/// matters because CI runs `wix` as the LocalSystem service account.
fn wix_eula_args() -> Vec<String> {
    match wix_major() {
        Some(major) if major >= 6 => vec!["-acceptEula".into(), format!("wix{major}")],
        _ => vec![],
    }
}

/// Whether a WiX extension is installed (`wix extension list --global`).
fn wix_has_ext(name: &str) -> bool {
    let mut args = vec!["extension".to_string(), "list".into(), "--global".into()];
    args.extend(wix_eula_args());
    std::process::Command::new("wix")
        .args(&args)
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains(name))
        .unwrap_or(false)
}

/// Wrap plain text as a minimal RichEdit-compatible RTF document — the dialect
/// the Windows Installer licence-agreement page can actually load (generic /
/// LibreOffice RTF often won't; the `\*\generator Riched20` tag is the tell).
fn rtf_document(text: &str) -> String {
    let mut body = String::with_capacity(text.len() + text.len() / 8);
    for line in text.replace('\r', "").split('\n') {
        for ch in line.chars() {
            match ch {
                '\\' => body.push_str("\\\\"),
                '{' => body.push_str("\\{"),
                '}' => body.push_str("\\}"),
                '\t' => body.push_str("\\tab "),
                c if c.is_ascii_graphic() || c == ' ' => body.push(c),
                c if (c as u32) < 0x80 => {} // other control chars — drop
                c => body.push_str(&format!("\\u{}?", c as u32)),
            }
        }
        body.push_str("\\par\n");
    }
    format!(
        "{{\\rtf1\\ansi\\ansicpg1252\\deff0\\nouicompat\
         {{\\fonttbl{{\\f0\\fnil\\fcharset0 Segoe UI;}}}}\
         {{\\*\\generator Riched20 10.0.19041}}\\viewkind4\\uc1\n\
         \\pard\\f0\\fs18\n{body}}}"
    )
}

fn wxs_source(exe_name: &str, has_icon: bool) -> String {
    let icon_block = if has_icon {
        "\n    <Icon Id=\"AppIcon.ico\" SourceFile=\"AppIcon.ico\" />\
         \n    <Property Id=\"ARPPRODUCTICON\" Value=\"AppIcon.ico\" />"
    } else {
        ""
    };
    let shortcut_icon = if has_icon {
        " Icon=\"AppIcon.ico\""
    } else {
        ""
    };

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs"
     xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">
  <Package
      Name="{name}"
      Manufacturer="{publisher}"
      Version="{version}"
      UpgradeCode="{upgrade_code}"
      Language="1031"
      Codepage="1252"
      InstallerVersion="500"
      Scope="perMachine">

    <SummaryInformation Description="{summary}" Manufacturer="{publisher}" />

    <MajorUpgrade DowngradeErrorMessage="Eine neuere Version von {name} ist bereits installiert." />
    <MediaTemplate EmbedCab="yes" />

    <Property Id="ARPHELPLINK" Value="{homepage}" />
    <Property Id="ARPURLINFOABOUT" Value="{homepage}" />{icon_block}

    <!-- A real install wizard: welcome, licence agreement, folder chooser,
         progress, finish (with a "launch now" checkbox). -->
    <ui:WixUI Id="WixUI_InstallDir" InstallDirectory="INSTALLFOLDER" />
    <UIRef Id="WixUI_ErrorProgressText" />
    <WixVariable Id="WixUILicenseRtf" Value="License.rtf" />

    <Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="{name} jetzt starten" />
    <Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOX" Value="1" />
    <CustomAction Id="LaunchApplication"
                  Directory="INSTALLFOLDER"
                  ExeCommand="[#AppExe]"
                  Execute="immediate"
                  Return="asyncNoWait"
                  Impersonate="yes" />
    <UI>
      <Publish Dialog="ExitDialog"
               Control="Finish"
               Event="DoAction"
               Value="LaunchApplication"
               Condition="WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed" />
    </UI>

    <StandardDirectory Id="ProgramFiles64Folder">
      <Directory Id="INSTALLFOLDER" Name="{name}" />
    </StandardDirectory>
    <StandardDirectory Id="ProgramMenuFolder" />

    <Feature Id="Main" Title="{name}" Level="1">
      <ComponentGroupRef Id="AppComponents" />
    </Feature>

    <ComponentGroup Id="AppComponents" Directory="INSTALLFOLDER">
      <Component Id="MainExecutable">
        <File Id="AppExe" Source="{exe_name}" KeyPath="yes">
          <Shortcut Id="StartMenuShortcut"
                    Directory="ProgramMenuFolder"
                    Name="{name}"
                    Description="{summary}"
                    WorkingDirectory="INSTALLFOLDER"{shortcut_icon} />
        </File>
      </Component>
      <Component Id="LicenseFile">
        <File Id="License" Source="LICENSE.txt" KeyPath="yes" />
      </Component>
      <Component Id="RegistryEntries">
        <RegistryValue Root="HKMU"
                       Key="Software\{publisher}\{name}"
                       Name="InstallDir"
                       Type="string"
                       Value="[INSTALLFOLDER]"
                       KeyPath="yes" />
      </Component>
    </ComponentGroup>
  </Package>
</Wix>
"#,
        name = xml_escape(meta::DISPLAY_NAME),
        publisher = xml_escape(meta::PUBLISHER),
        version = meta::numeric_version(),
        upgrade_code = meta::WIX_UPGRADE_CODE,
        summary = xml_escape(meta::SUMMARY),
        homepage = xml_escape(meta::HOMEPAGE),
        icon_block = icon_block,
        exe_name = exe_name,
        shortcut_icon = shortcut_icon,
    )
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn io(e: std::io::Error) -> String {
    format!("{e}")
}

#[cfg(test)]
mod tests {
    fn ctx(target: Option<&str>) -> crate::bundle::Context {
        crate::bundle::Context {
            binary: std::path::PathBuf::new(),
            out_dir: std::path::PathBuf::new(),
            formats: None,
            sign: None,
            target: target.map(String::from),
            have_icon: false,
        }
    }

    #[test]
    fn win_arch_maps_the_target_triple() {
        assert_eq!(
            super::win_arch(&ctx(Some("x86_64-pc-windows-gnullvm"))).unwrap(),
            "x64"
        );
        assert_eq!(
            super::win_arch(&ctx(Some("aarch64-pc-windows-gnullvm"))).unwrap(),
            "arm64"
        );
        assert!(super::win_arch(&ctx(Some("mips64-pc-windows-gnu"))).is_err());
    }

    #[test]
    fn wxs_wires_the_install_wizard() {
        let wxs = super::wxs_source("App.exe", true);
        for needle in [
            r#"xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui""#,
            r#"<ui:WixUI Id="WixUI_InstallDir" InstallDirectory="INSTALLFOLDER" />"#,
            r#"<WixVariable Id="WixUILicenseRtf" Value="License.rtf" />"#,
            "WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT",
            r#"Id="LaunchApplication""#,
            r#"ExeCommand="[#AppExe]""#,
            r#"Event="DoAction""#,
        ] {
            assert!(wxs.contains(needle), "wxs missing {needle:?}");
        }
        // Tags balance (crude well-formedness guard).
        assert_eq!(
            wxs.matches('<').count(),
            wxs.matches('>').count(),
            "unbalanced angle brackets"
        );
    }

    #[test]
    fn rtf_document_is_balanced_and_escaped() {
        let rtf = super::rtf_document("line one\n{braces} and a \\ backslash\n\ttabbed");
        assert!(rtf.starts_with("{\\rtf1"));
        assert_eq!(
            rtf.matches('{').count(),
            rtf.matches('}').count(),
            "unbalanced RTF groups"
        );
        assert!(rtf.contains("\\{braces\\}"));
        assert!(rtf.contains("a \\\\ backslash"));
        assert!(rtf.contains("\\tab tabbed"));
        assert!(rtf.contains("\\par\n"));
    }
}
