//! Windows packaging: a portable folder always, plus a WiX-authored `.msi`.
//!
//! The app binary is self-contained, so the "portable" output is just the
//! `.exe` (+ licence). The `.msi` is generated by writing a `.wxs` authoring
//! file and invoking the **WiX Toolset v4** (`wix build`) when it's on `PATH`;
//! without WiX we still emit the `.wxs` so it can be built on a machine that
//! has it.

use crate::bundle::Context;
use crate::util::{copy, fresh_dir, have, report, try_run, workspace_root};
use crate::{icon, meta};

pub fn bundle(cx: &Context) -> Result<(), String> {
    // ── portable folder ────────────────────────────────────────────────────
    let portable = cx
        .out_dir
        .join(format!("{}-{}-x64", meta::SLUG, meta::numeric_version()));
    fresh_dir(&portable).map_err(io)?;
    // The shipped/branded name (meta::DISPLAY_NAME), not the raw cargo build
    // artifact's kebab-case name.
    copy(
        &cx.binary,
        &portable.join(format!("{}.exe", meta::DISPLAY_NAME)),
    )
    .map_err(io)?;
    copy(
        &workspace_root().join("crates/dtb-ke-ui/assets/AGPL-3.0.txt"),
        &portable.join("LICENSE.txt"),
    )
    .ok();
    report(&portable);

    // ── WiX authoring ─────────────────────────────────────────────────────
    let staging = cx.out_dir.join("wix");
    fresh_dir(&staging).map_err(io)?;
    let exe_name = format!("{}.exe", meta::DISPLAY_NAME);
    copy(&cx.binary, &staging.join(&exe_name)).map_err(io)?;
    copy(
        &workspace_root().join("crates/dtb-ke-ui/assets/AGPL-3.0.txt"),
        &staging.join("LICENSE.rtf.txt"),
    )
    .ok();

    let has_icon = cx.have_icon && icon::ico_path().exists();
    if has_icon {
        copy(&icon::ico_path(), &staging.join("AppIcon.ico")).map_err(io)?;
    }

    let wxs = staging.join("Package.wxs");
    std::fs::write(&wxs, wxs_source(&exe_name, has_icon)).map_err(io)?;
    report(&wxs);

    // ── build the .msi ────────────────────────────────────────────────────
    if !cx.wants("msi") {
        eprintln!("dtb-ke-bundle: skipping .msi (--formats doesn't include it)");
        return Ok(());
    }
    if !have("wix") {
        eprintln!(
            "dtb-ke-bundle: `wix` not on PATH — wrote {} but did not build the .msi.\n\
             Install the WiX Toolset v4 (`dotnet tool install --global wix`) and re-run, \
             or build it elsewhere with `wix build {}`.",
            wxs.display(),
            wxs.display()
        );
        return Ok(());
    }

    let msi = cx.out_dir.join(format!(
        "{}-{}-x64.msi",
        meta::SLUG,
        meta::numeric_version()
    ));
    let mut args = vec![
        "build".to_string(),
        wxs.to_string_lossy().into_owned(),
        "-arch".into(),
        "x64".into(),
        "-o".into(),
        msi.to_string_lossy().into_owned(),
    ];
    // WiX UI extension for a basic install dialog set, when available.
    if wix_has_ext("WixToolset.UI.wixext") {
        args.push("-ext".into());
        args.push("WixToolset.UI.wixext".into());
    }
    try_run(
        "wix",
        &args.iter().map(String::as_str).collect::<Vec<_>>(),
        &staging,
    )?;
    report(&msi);
    Ok(())
}

/// Whether a WiX extension is installed (`wix extension list`).
fn wix_has_ext(name: &str) -> bool {
    std::process::Command::new("wix")
        .args(["extension", "list", "--global"])
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains(name))
        .unwrap_or(false)
}

fn wxs_source(exe_name: &str, has_icon: bool) -> String {
    let icon_block = if has_icon {
        "\n    <Icon Id=\"AppIcon.ico\" SourceFile=\"AppIcon.ico\" />\
         \n    <Property Id=\"ARPPRODUCTICON\" Value=\"AppIcon.ico\" />"
    } else {
        ""
    };
    let shortcut_icon = if has_icon {
        " Icon=\"AppIcon.ico\""
    } else {
        ""
    };

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package
      Name="{name}"
      Manufacturer="{publisher}"
      Version="{version}"
      UpgradeCode="{upgrade_code}"
      Language="1031"
      Codepage="1252"
      InstallerVersion="500"
      Scope="perMachine">

    <SummaryInformation Description="{summary}" Manufacturer="{publisher}" />

    <MajorUpgrade DowngradeErrorMessage="Eine neuere Version von {name} ist bereits installiert." />
    <MediaTemplate EmbedCab="yes" />

    <Property Id="ARPHELPLINK" Value="{homepage}" />
    <Property Id="ARPURLINFOABOUT" Value="{homepage}" />{icon_block}

    <StandardDirectory Id="ProgramFiles64Folder">
      <Directory Id="INSTALLFOLDER" Name="{name}" />
    </StandardDirectory>
    <StandardDirectory Id="ProgramMenuFolder" />

    <Feature Id="Main" Title="{name}" Level="1">
      <ComponentGroupRef Id="AppComponents" />
    </Feature>

    <ComponentGroup Id="AppComponents" Directory="INSTALLFOLDER">
      <Component Id="MainExecutable">
        <File Id="AppExe" Source="{exe_name}" KeyPath="yes">
          <Shortcut Id="StartMenuShortcut"
                    Directory="ProgramMenuFolder"
                    Name="{name}"
                    Description="{summary}"
                    WorkingDirectory="INSTALLFOLDER"{shortcut_icon} />
        </File>
      </Component>
      <Component Id="LicenseFile">
        <File Id="License" Source="LICENSE.rtf.txt" KeyPath="yes" />
      </Component>
      <Component Id="RegistryEntries">
        <RegistryValue Root="HKMU"
                       Key="Software\{publisher}\{name}"
                       Name="InstallDir"
                       Type="string"
                       Value="[INSTALLFOLDER]"
                       KeyPath="yes" />
      </Component>
    </ComponentGroup>
  </Package>
</Wix>
"#,
        name = xml_escape(meta::DISPLAY_NAME),
        publisher = xml_escape(meta::PUBLISHER),
        version = meta::numeric_version(),
        upgrade_code = meta::WIX_UPGRADE_CODE,
        summary = xml_escape(meta::SUMMARY),
        homepage = xml_escape(meta::HOMEPAGE),
        icon_block = icon_block,
        exe_name = exe_name,
        shortcut_icon = shortcut_icon,
    )
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn io(e: std::io::Error) -> String {
    format!("{e}")
}
