name: 'Publish Release'

on:
  push:
    branches:
      - production

jobs:
  publish-release:
    environment: Release
    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
            target: "aarch64-apple-darwin"
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
            target: "x86_64-apple-darwin"
          - platform: 'windows-latest'
            args: ''
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.89.0
          targets: ${{ matrix.target }}

      - name: Install Node dependencies (npm)
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4

      - name: Load Environment Variables (Release Notes)
        uses: xom9ikk/dotenv@v2
        with:
          path: environment
          mode: production

      - name: Run Tauri Build (Windows & Linux)
        if: matrix.platform != 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          tagName: dtb-kampfrichtereinsatzplaene-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'DTB Kampfrichtereinsatzpläne v__VERSION__'
          releaseBody: ${{ env.RELEASE_BODY }}
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}

      - name: Run Tauri Build (macOS)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          tauriScript: "npm run tauri-macos"
          tagName: dtb-kampfrichtereinsatzplaene-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'DTB Kampfrichtereinsatzpläne v__VERSION__'
          releaseBody: ${{ env.RELEASE_BODY }}
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
